In [14]:
import pandas as pd
import numpy as np 
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix,classification_report

In [15]:
df = pd.read_csv("income_evaluation.csv")
df.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   age              32561 non-null  int64
 1    workclass       32561 non-null  object
 2    fnlwgt          32561 non-null  int64
 3    education       32561 non-null  object
 4    education-num   32561 non-null  int64
 5    marital-status  32561 non-null  object
 6    occupation      32561 non-null  object
 7    relationship    32561 non-null  object
 8    race            32561 non-null  object
 9    sex             32561 non-null  object
 10   capital-gain    32561 non-null  int64
 11   capital-loss    32561 non-null  int64
 12   hours-per-week  32561 non-null  int64
 13   native-country  32561 non-null  object
 14   income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

In [17]:
df.columns

Index(['age', ' workclass', ' fnlwgt', ' education', ' education-num',
       ' marital-status', ' occupation', ' relationship', ' race', ' sex',
       ' capital-gain', ' capital-loss', ' hours-per-week', ' native-country',
       ' income'],
      dtype='object')

In [18]:
np.unique(df[' income'])

array([' <=50K', ' >50K'], dtype=object)

In [19]:
df.drop(' fnlwgt', axis=1, inplace=True)

In [20]:
##to deal with space 
col_name = ['age', 'workclass',  'education', 'education-num',
       'marital-status', 'occupation', 'relationship', 'race', 'sex',
       'capital-gain', 'capital-loss', 'hours-per-week', 'native-country',
       'income']

df.columns = col_name
df.columns

Index(['age', 'workclass', 'education', 'education-num', 'marital-status',
       'occupation', 'relationship', 'race', 'sex', 'capital-gain',
       'capital-loss', 'hours-per-week', 'native-country', 'income'],
      dtype='object')

In [21]:
# df.isnull().sum()
df.loc[df["workclass"]==" ?"]

,age,workclass,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
27,54,?,Some-college,10,Married-civ-spouse,?,Husband,Asian-Pac-Islander,Male,0,0,60,South,>50K
61,32,?,7th-8th,4,Married-spouse-absent,?,Not-in-family,White,Male,0,0,40,?,<=50K
69,25,?,Some-college,10,Never-married,?,Own-child,White,Male,0,0,40,United-States,<=50K
77,67,?,10th,6,Married-civ-spouse,?,Husband,White,Male,0,0,2,United-States,<=50K
106,17,?,10th,6,Never-married,?,Own-child,White,Female,34095,0,32,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32530,35,?,Bachelors,13,Married-civ-spouse,?,Wife,White,Female,0,0,55,United-States,>50K
32531,30,?,Bachelors,13,Never-married,?,Not-in-family,Asian-Pac-Islander,Female,0,0,99,United-States,<=50K
32539,71,?,Doctorate,16,Married-civ-spouse,?,Husband,White,Male,0,0,10,United-States,>50K
32541,41,?,HS-grad,9,Separated,?,Not-in-family,Black,Female,0,0,32,United-States,<=50K
32542,72,?,HS-grad,9,Married-civ-spouse,?,Husband,White,Male,0,0,25,United-States,<=50K

In [22]:
df.loc[df["workclass"]==" ?","workclass"] = np.nan
df.loc[df["occupation"]==" ?","occupation"] = np.nan
df.loc[df["native-country"]==" ?","native-country"] = np.nan

In [23]:
df.isnull().sum()
df.dropna(inplace=True)

In [24]:
##to change our income column data type to int
df['income'] = df['income'].map({' <=50K': 0, ' >50K': 1})
df.head()

,age,workclass,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,0
1,50,Self-emp-not-inc,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,0
2,38,Private,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,0
3,53,Private,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,0
4,28,Private,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,0

In [25]:
df["income"].value_counts()

income
0    22654
1     7508
Name: count, dtype: int64

In [26]:
##data balance of income column

In [27]:
cat_col = df.select_dtypes(include="object")
cat_col.head()

,workclass,education,marital-status,occupation,relationship,race,sex,native-country
0,State-gov,Bachelors,Never-married,Adm-clerical,Not-in-family,White,Male,United-States
1,Self-emp-not-inc,Bachelors,Married-civ-spouse,Exec-managerial,Husband,White,Male,United-States
2,Private,HS-grad,Divorced,Handlers-cleaners,Not-in-family,White,Male,United-States
3,Private,11th,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,United-States
4,Private,Bachelors,Married-civ-spouse,Prof-specialty,Wife,Black,Female,Cuba

In [28]:
num_col = df.select_dtypes(exclude="object")
num_col.head()

   age  education-num  capital-gain  capital-loss  hours-per-week  income
0   39             13          2174             0              40       0
1   50             13             0             0              13       0
2   38              9             0             0              40       0
3   53              7             0             0              40       0
4   28             13             0             0              40       0

In [29]:
##label encoding 
# from sklearn.preprocessing import LabelEncoder
# def label_encoder(a):
#     le = LabelEncoder()
#     df[a] = le.fit_transform(df[a])

#label encoding on cat col 
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
cat_col_encoded = cat_col.apply(le.fit_transform)
cat_col_encoded

,workclass,education,marital-status,occupation,relationship,race,sex,native-country
0,5,9,4,0,1,4,1,38
1,4,9,2,3,0,4,1,38
2,2,11,0,5,1,4,1,38
3,2,1,2,5,0,2,1,38
4,2,9,2,9,5,2,0,4
...,...,...,...,...,...,...,...,...
32556,2,7,2,12,5,4,0,38
32557,2,11,2,6,0,4,1,38
32558,2,11,6,0,4,4,0,38
32559,2,11,4,0,3,4,1,38
32560,3,11,2,3,5,4,0,38

In [30]:
# # cat_col.apply(label_encoder)
# cat_col.columns
# label_list = ['workclass', 'education', 'marital-status', 'occupation',
#        'relationship', 'race', 'sex', 'native-country']
# for i in label_list:
#     label_encoder(i)

In [31]:
final_df = pd.concat([cat_col_encoded, num_col], axis=1)

In [32]:
##x and y 
x = final_df.drop("income",axis=1)
y = final_df["income"]

In [33]:
##train test split 
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, 
                                                    y,
                                                      test_size=0.2,
                                                        random_state=42)

In [34]:
##standard scaler -- normalise -- range 
##mean - 0 std - 1
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [35]:
#svc
from sklearn.svm import SVC
svc = SVC()
svc.fit(x_train_scaled,y_train)

SVC()

In [36]:
svc.score(x_test_scaled,y_test)

0.8480026520802254

In [37]:
svc.score(x_train_scaled,y_train)

0.8509677151974802

In [ ]:
#import grid search cv
from sklearn.model_selection import GridSearchCV
grid = {
    "C" : [0.01,0.1,1,10],
    "kernel" : ["linear","rbf","ploy","sigmoid"],
    "degree" : [1,3,5,7],
    "gamma" : [0.01,1]
}
svm = SVC()
svm_cv = GridSearchCV(svm,grid,cv=5)
svm_cv.fit(x_train_scaled,y_train)

In [ ]:
svm_cv.best_params_
svm_cv.best_score_